const SPREADSHEET_ID=SpreadsheetApp.getActiveSpreadsheet().getId();
const COMMISSION_RATE=0.10;
function out(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
function sh(n){return SpreadsheetApp.openById(SPREADSHEET_ID).getSheetByName(n)}
function rows(n){const s=sh(n);if(!s||s.getLastRow()<2)return[];const v=s.getDataRange().getValues(),h=v.shift();return v.map(r=>Object.fromEntries(h.map((k,i)=>[String(k),r[i]])))}
function uid(p){return p+"_"+Date.now()+"_"+Math.floor(Math.random()*10000)}
function hash(v){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(v),Utilities.Charset.UTF_8).map(b=>("0"+(b&255).toString(16)).slice(-2)).join("")}
function appendObj(sheetName,obj){const s=sh(sheetName);if(!s)throw new Error('Sheet not found: '+sheetName);const h=s.getRange(1,1,1,s.getLastColumn()).getValues()[0];s.appendRow(h.map(k=>obj[String(k)]!==undefined?obj[String(k)]:''))}
function doGet(e){try{const a=e.parameter.action,p=e.parameter;
if(a==="products")return out({success:true,products:rows("Products")});
if(a==="categories")return out({success:true,categories:rows("Categories")});
if(a==="sellers")return out({success:true,sellers:rows("Sellers")});
if(a==="users")return out({success:true,users:rows("Users")});
if(a==="orders"){let x=rows("Orders");if(p.userId)x=x.filter(r=>String(r.UserID)===String(p.userId));if(p.sellerId)x=x.filter(r=>String(r.SellerID)===String(p.sellerId));return out({success:true,orders:x})}
if(a==="cart"){const c=rows("Cart").filter(r=>String(r.UserID)===String(p.userId));const ps=rows("Products");const cart=c.map(x=>{const q=ps.find(z=>String(z.ProductID)===String(x.ProductID));return Object.assign({},x,q?{ProductName:q.ProductName,Price:q.Price,ImageURL:q.ImageURL,SellerID:q.SellerID}:{});});return out({success:true,cart})}
if(a==="wishlist")return out({success:true,wishlist:rows("Wishlist").filter(r=>String(r.UserID)===String(p.userId))});
if(a==="reviews")return out({success:true,reviews:rows("Reviews")});
if(a==="notifications")return out({success:true,notifications:rows("Notifications").filter(r=>!p.userId||String(r.UserID)===String(p.userId))});
if(a==="withdrawals")return out({success:true,withdrawals:rows("Withdrawals").filter(r=>!p.sellerId||String(r.SellerID)===String(p.sellerId))});
if(a==="sellerBalances"){const sid=p.sellerId;const sales=rows("Orders").filter(r=>String(r.SellerID)===String(sid)&&String(r.OrderStatus).toLowerCase()==="delivered").reduce((t,r)=>t+Number(r.TotalAmount||r.Amount||0),0);const approved=rows("Withdrawals").filter(r=>String(r.SellerID)===String(sid)&&String(r.Status).toLowerCase()==="approved").reduce((t,r)=>t+Number(r.Amount||0),0);return out({success:true,balance:{AvailableBalance:Math.max(0,sales*(1-COMMISSION_RATE)-approved),TotalSales:sales,TotalCommission:sales*COMMISSION_RATE}})}
return out({success:false,message:"Unknown action"})}catch(err){return out({success:false,message:String(err)})}}
function doPost(e){let d;try{d=JSON.parse(e.postData.contents||"{}")}catch(err){return out({success:false,message:"Invalid JSON"})}try{const a=d.action;
if(a==="register"){const u=rows("Users");if(u.some(x=>String(x.Email).toLowerCase()===String(d.email).toLowerCase()))return out({success:false,message:"Email already registered"});const userId=uid("USR");appendObj("Users",{"User ID":userId,UserID:userId,Name:d.name,Email:d.email,Phone:d.phone,PasswordHash:hash(d.password)});if(String(d.role||"buyer").toLowerCase()==="seller"){const sellerId=uid("SEL");appendObj("Sellers",{SellerID:sellerId,UserID:userId,StoreName:d.storeName||((d.name||"")+" Store"),OwnerName:d.name||"",Email:d.email||"",Phone:d.phone||"",Address:d.storeAddress||"",Status:"Approved",CommissionRate:COMMISSION_RATE,CreatedAt:new Date()});return out({success:true,message:"Seller account created successfully! You can now login as Seller."})}return out({success:true,message:"Buyer account created successfully! You can now login as Buyer."})}
if(a==="login"){const u=rows("Users").find(x=>String(x.Email).toLowerCase()===String(d.email).toLowerCase()&&String(x.PasswordHash)===hash(d.password));if(!u)return out({success:false,message:"Invalid email or password"});const id=u["User ID"]||u.UserID,s=rows("Sellers").find(x=>String(x.UserID)===String(id));const role=String(u.Email).toLowerCase()==="admin@maxstore.lk"?"admin":s?"seller":"buyer";return out({success:true,user:{userId:id,name:u.Name,email:u.Email,role,sellerId:s?.SellerID||""}})}
if(a==="addProduct"){appendObj("Products",{ProductID:d.productID||uid("PRD"),ProductName:d.ProductName||"",MainCategory:d.MainCategory||"",SubCategory:d.SubCategory||"",Price:Number(d.Price||0),Stock:Number(d.Stock||0),SellerID:d.sellerID||"",ImageURL:d.ImageURL||"",Description:d.Description||"",Status:d.Status||"Active"});return out({success:true,message:"Product added"})}
if(a==="updateProduct"){const s=sh("Products"),v=s.getDataRange().getValues(),h=v[0],ix=h.indexOf("ProductID");for(let i=1;i<v.length;i++)if(String(v[i][ix])===String(d.productID)){["ProductName","MainCategory","SubCategory","Price","Stock","ImageURL","Description","Status"].forEach(k=>{const j=h.indexOf(k);if(j>=0&&d[k]!==undefined)s.getRange(i+1,j+1).setValue(d[k])});return out({success:true,message:"Product updated"})}return out({success:false,message:"Product not found"})}
if(a==="deleteProduct"){const s=sh("Products"),v=s.getDataRange().getValues(),h=v[0],ix=h.indexOf("ProductID");for(let i=v.length-1;i>0;i--)if(String(v[i][ix])===String(d.productID)){s.deleteRow(i+1);return out({success:true,message:"Product deleted"})}return out({success:false,message:"Product not found"})}
if(a==="addCart"){const c=rows("Cart").find(x=>String(x.UserID)===String(d.userId)&&String(x.ProductID)===String(d.productId));if(c){const s=sh("Cart"),v=s.getDataRange().getValues(),h=v[0],ix=h.indexOf("CartID"),iq=h.indexOf("Quantity");for(let i=1;i<v.length;i++)if(String(v[i][ix])===String(c.CartID))s.getRange(i+1,iq+1).setValue(Number(c.Quantity||0)+Number(d.quantity||1));}else appendObj("Cart",{CartID:uid("CRT"),UserID:d.userId,ProductID:d.productId,Quantity:Number(d.quantity||1),CreatedAt:new Date()});return out({success:true,message:"Added to cart"})}
if(a==="removeCart"){const s=sh("Cart"),v=s.getDataRange().getValues(),h=v[0],iu=h.indexOf("UserID"),ip=h.indexOf("ProductID");for(let i=v.length-1;i>0;i--)if(String(v[i][iu])===String(d.userId)&&String(v[i][ip])===String(d.productId)){s.deleteRow(i+1);return out({success:true,message:"Removed from cart"})}return out({success:false,message:"Cart item not found"})}
if(a==="clearCart"){const s=sh("Cart"),v=s.getDataRange().getValues(),h=v[0],iu=h.indexOf("UserID");for(let i=v.length-1;i>0;i--)if(String(v[i][iu])===String(d.userId))s.deleteRow(i+1);return out({success:true,message:"Cart cleared"})}
if(a==="createOrder"){const cart=rows("Cart").filter(x=>String(x.UserID)===String(d.userId));if(!cart.length)return out({success:false,message:"Cart is empty"});const products=rows("Products");const orderId=uid("ORD"),created=new Date();let total=0;for(const item of cart){const p=products.find(x=>String(x.ProductID)===String(item.ProductID));if(!p)continue;const qty=Number(item.Quantity||1),price=Number(p.Price||0),amount=price*qty;total+=amount;appendObj("OrderItems",{OrderItemID:uid("ITM"),OrderID:orderId,ProductID:p.ProductID,SellerID:p.SellerID,Quantity:qty,Price:price,Amount:amount});appendObj("Orders",{OrderID:orderId,UserID:d.userId,SellerID:p.SellerID,TotalAmount:amount,PaymentMethod:d.paymentMethod||"COD",PaymentStatus:(String(d.paymentMethod||"COD").toLowerCase()==="cod"?"Pending":"Pending"),OrderStatus:"Pending",ShippingAddress:d.shippingAddress||"",CreatedAt:created,UpdatedAt:created});}
const cs=sh("Cart"),cv=cs.getDataRange().getValues(),ch=cv[0],ciu=ch.indexOf("UserID");for(let i=cv.length-1;i>0;i--)if(String(cv[i][ciu])===String(d.userId))cs.deleteRow(i+1);return out({success:true,message:"Order placed successfully!",orderId,total})}
if(a==="withdraw"){appendObj("Withdrawals",{WithdrawalID:uid("WD"),SellerID:d.sellerID||d.sellerId,Amount:Number(d.amount||0),Method:d.method||"",Details:d.details||"",Status:"Pending",CreatedAt:new Date()});return out({success:true,message:"Withdrawal request submitted"})}
if(a==="updateOrderStatus"){const s=sh("Orders"),v=s.getDataRange().getValues(),h=v[0],ix=h.indexOf("OrderID"),st=h.indexOf("OrderStatus");for(let i=1;i<v.length;i++)if(String(v[i][ix])===String(d.orderId)){s.getRange(i+1,st+1).setValue(d.status);return out({success:true,message:"Order updated"})}return out({success:false,message:"Order not found"})}
return out({success:false,message:"Unknown action"})}catch(err){return out({success:false,message:String(err)})}}
